# Usa a imagem base do NGINX
FROM nginx:alpine

# Remove o arquivo de configuração padrão do NGINX
RUN rm /etc/nginx/conf.d/default.conf

# Copia o arquivo 'default.conf' para o local certo dentro do container
COPY default.conf /etc/nginx/conf.d/